---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="kali"
  - version="" distro="kali"
  - version="devel" distro="kali"

matrix:
  allow_failures:
    - env: version="devel" distro="kali"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - ansible-galaxy install --role-file requirements.yml --roles-path roles

script:
  - ansible-playbook ./playbook.yml --connection=local --syntax-check
  - ansible-playbook ./playbook.yml --connection=local --sudo
  - "ansible-playbook ./playbook.yml --connection=local --sudo | tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt &amp;&amp; (echo 'Idempotence test: pass' &amp;&amp; exit 0) || (echo 'Idempotence test: fail' &amp;&amp; exit 1)"


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
