---
sudo: required
language: python
services: docker

cache:
  - pip

before_install:
  - 'sudo docker pull kalilinux/kali-linux-docker:latest'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.kali-latest --tag=kali-latest:ansible travis'

install:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/root/hotwax:rw kali-latest:ansible > "${container_id}"'

  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install --role-file /root/hotwax/requirements.yml --roles-path /root/hotwax/roles'
  # - ansible-galaxy install --role-file requirements.yml --roles-path roles

script:
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/hotwax/playbook.yml --syntax-check'
  # - ansible-playbook ./playbook.yml --connection=local --syntax-check
  # - ansible-playbook ./playbook.yml --connection=local --sudo
  # - "ansible-playbook ./playbook.yml --connection=local --sudo | tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt &amp;&amp; (echo 'Idempotence test: pass' &amp;&amp; exit 0) || (echo 'Idempotence test: fail' &amp;&amp; exit 1)"


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
