---
# https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy the lin/winPEAS from repository
  git:
    repo: "https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite"
    dest: /opt/peass
    update: yes
