---
# https://github.com/sshuttle/sshuttle
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy sshuttle from repository
  git:
    repo: "https://github.com/sshuttle/sshuttle"
    dest: /opt/sshuttle
    update: yes

- name: Install sshuttle via setup.py
  shell:
    chdir: /opt/sshuttle
    cmd: sudo ./setup.py install
