---
# https://github.com/sshuttle/sshuttle
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy sshuttle from repository
  git:
    repo: "https://github.com/sshuttle/sshuttle"
    dest: /opt/sshuttle
    update: yes
    force: yes

- name: Force python3 as the default interpreter for sshuttle
  lineinfile:
    path: /opt/sshuttle/setup.py
    regexp: "#!/usr/bin/env python"
    line: "#!/usr/bin/python3"

- name: Install sshuttle via setup.py
  shell:
    chdir: /opt/sshuttle
    cmd: sudo ./setup.py install
