---
# https://github.com/g0tmi1k/msfpc
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy msfpc from repository
  git:
    repo: "https://github.com/g0tmi1k/msfpc.git"
    dest: /opt/msfpc
    update: yes
