---
# Per https://forums.offensive-security.com/showthread.php?10243-4-3-2-enum4linux-errors-in-Kali-Linux/page2
- name: Create link for polenum.py
  file:
    src: /usr/bin/polenum
    dest: /usr/bin/polenum.py
    state: link