---
- set_fact:
    homefolder: "{{'/home/' + username + '/'}}"
  #when: "{{username != 'root'}}"
  when: "username != 'root'"

- set_fact:
    homefolder: "/root/"
  #when: "{{username == 'root'}}"
  when: "username == 'root'"
  
